from pydantic import BaseModel
from typing import Optional


# -------------------------
# Requête pour lancer un scan Git
# -------------------------
class GitScanRequest(BaseModel):

    # URL du repository Git à analyser
    repo_url: str

    # Token GitHub optionnel (utile si le repo est privé)
    github_token: Optional[str] = None


# -------------------------
# Requête pour appliquer un patch manuel
# -------------------------
class ApplyFixRequest(BaseModel):

    # Repository cible
    repo_url: str

    # Token GitHub obligatoire pour pouvoir push et créer une PR
    github_token: str

    # Branche de base sur laquelle on applique le correctif
    # Par défaut on utilise "main"
    base_branch: Optional[str] = "main"

    # Patch diff à appliquer (généré par l'outil ou fourni manuellement)
    patch_diff: str

    # Titre de la Pull Request créée automatiquement
    title: Optional[str] = "SecureScan: apply automated fix"

    # Description de la Pull Request
    body: Optional[str] = "This PR was generated by SecureScan."


# -------------------------
# Requête pour appliquer un fix automatique depuis la base
# -------------------------
class AutoFixRequest(BaseModel):

    # Repository cible
    repo_url: str

    # Token GitHub nécessaire pour créer une branche et une PR
    github_token: str

    # ID du finding (vulnérabilité) enregistré en base
    # Sert à récupérer automatiquement le patch correspondant
    finding_id: str

    # Branche de base sur laquelle le fix sera appliqué
    base_branch: Optional[str] = "main"

    # Titre de la PR générée
    title: Optional[str] = "SecureScan: apply automated fix"

    # Message de description de la PR
    body: Optional[str] = "This PR was generated by SecureScan."