import { getJson, postJson, postFormData } from "./client";

function normalizeSettled(toolName, settled) {
  if (settled.status === "fulfilled") return settled.value;
  return { tool: toolName, error: settled.reason?.message || String(settled.reason) };
}

// Lance Semgrep sur un fichier ZIP
export async function scanSemgrepZip(zipFile) {
  const fd = new FormData();
  fd.append("file", zipFile);
  return postFormData("/scan/semgrep", fd);
}

// Lance Bandit sur un fichier ZIP
export async function scanBanditZip(zipFile) {
  const fd = new FormData();
  fd.append("file", zipFile);
  return postFormData("/scan/bandit", fd);
}

// Lance TruffleHog sur un fichier ZIP
export async function scanTrufflehogZip(zipFile) {
  const fd = new FormData();
  fd.append("file", zipFile);
  return postFormData("/scan/trufflehog", fd);
}

// Lance Semgrep sur un repo Git
export async function scanSemgrepGit(repo_url, github_token) {
  return postJson("/scan/semgrep/git", {
    repo_url,
    github_token: github_token || null,
  });
}

// Lance Bandit sur un repo Git
export async function scanBanditGit(repo_url, github_token) {
  return postJson("/scan/bandit/git", {
    repo_url,
    github_token: github_token || null,
  });
}

// Lance TruffleHog sur un repo Git
export async function scanTrufflehogGit(repo_url, github_token) {
  return postJson("/scan/trufflehog/git", {
    repo_url,
    github_token: github_token || null,
  });
}

// Lance tous les outils en parallèle sur un ZIP
export async function scanZipAll(file) {
  const fd = new FormData();
  fd.append("file", file);

  const [semgrep, bandit, trufflehog] = await Promise.allSettled([
    postFormData("/scan/semgrep", fd),
    postFormData("/scan/bandit", fd),
    postFormData("/scan/trufflehog", fd),
  ]);

  return {
    semgrepResult: normalizeSettled("semgrep", semgrep),
    banditResult: normalizeSettled("bandit", bandit),
    trufflehogResult: normalizeSettled("trufflehog", trufflehog),
  };
}

// Lance tous les outils en parallèle sur un repo Git
export async function scanGitAll(repo_url, github_token) {
  const [semgrep, bandit, trufflehog] = await Promise.allSettled([
    postJson("/scan/semgrep/git", { repo_url, github_token: github_token || null }),
    postJson("/scan/bandit/git", { repo_url, github_token: github_token || null }),
    postJson("/scan/trufflehog/git", { repo_url, github_token: github_token || null }),
  ]);

  return {
    semgrepResult: normalizeSettled("semgrep", semgrep),
    banditResult: normalizeSettled("bandit", bandit),
    trufflehogResult: normalizeSettled("trufflehog", trufflehog),
  };
}

// Liste les scans récents
export function listScans(limit = 10) {
  return getJson(`/scans?limit=${limit}`);
}

// Récupère les détails d'un scan avec ses findings
export function getScanDetails(scanId) {
  return getJson(`/scans/${scanId}`);
}

// Crée une Pull Request pour corriger une vulnérabilité
export function autoFixGithub({ repo_url, github_token, finding_id, base_branch, title, body }) {
  return postJson("/fix/auto/github", {
    repo_url,
    github_token,
    finding_id,
    base_branch: base_branch || "main",
    title: title || "SecureScan: apply automated fix",
    body: body || "This PR was generated by SecureScan.",
  });
}
